dist: bionic
language: python
python: '3.7'

services:
  - docker
  
env:
  - DISTROS=ubuntu,debian,fedora

before_install:
  - openssl aes-256-cbc -K $encrypted_ae4a4597577a_key -iv $encrypted_ae4a4597577a_iv -in .ansible-vault-password.enc -out .ansible-vault-password -d
  - sudo apt-get update -qq

install:
  - pip3 install -r requirements.txt

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
