dist: bionic
language: python
python: '3.7'
env:
- JVM_PROVIDER=openjdk JAVA_VERSION=8 DISTROS=ubuntu,debian,fedora
- JVM_PROVIDER=openjdk JAVA_VERSION=11 DISTROS=ubuntu,fedora
before_install:
- openssl aes-256-cbc -K $encrypted_ae4a4597577a_key -iv $encrypted_ae4a4597577a_iv
  -in .ansible-vault-password.enc -out .ansible-vault-password -d
- sudo apt-get update -qq
install:
- pip3 install ansible pyopenssl cryptography
before_script:
- make setup
script:
- make install ADD_ANSIBLE_PLAYBOOK_OPTS="--syntax-check"
- make install
- 'make install | grep -q ''changed=0.*failed=0'' && (echo ''Idempotence: PASS'' && exit 0) || (echo ''Idempotence: FAIL'' && exit 1)'
after_script:
- make teardown
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
