---
- name: apply | install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - unzip
    - tar
    - wget
    - ntp
    - htop
    - bash-completion
    - screen
    - tree
    - jq
    - iperf
    - vim
    - nmap
