# ansible-role-system/tasks/apply-Debian.yml
---
- name: apply | install python3
  raw: apt install -y python3
  changed_when: no

- name: apply | update apt cache
  apt:
    update_cache: yes
  changed_when: no
