---
- include_tasks: apply-{{ ansible_os_family }}.yml

- name: apply | install packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages[ansible_os_family] }}"

- name: apply | upload ssh banner
  copy:
    src: banner
    dest: "/etc/ssh/banner"

- name: apply | set ssh banner
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: '\s*#*\s*Banner .*'
    line: "Banner /etc/ssh/banner"
  notify:
    - restart sshd
