---
- include_tasks: apply-{{ ansible_os_family }}.yml

- name: apply | install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - unzip
    - tar
    - wget
    - ntp
    - htop
    - bash-completion
    - screen
    - tree
    - jq
    - iperf
    - vim
    - nmap
    - rsyslog
    - python3-pip

- name: apply | upload ssh banner
  copy:
    src: banner
    dest: "/etc/ssh/banner"

- name: apply | set ssh banner
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: '\s*#*\s*Banner .*'
    line: "Banner /etc/ssh/banner"
  notify:
    - restart sshd
