---
# Create special log file for ansible tasks.
- name: configure | rsyslog
  copy:
    src: rsyslog.conf
    dest: /etc/rsyslog.d/51-ansible.conf
    mode: 600
  notify:
    - restart rsyslog

- name: configure | disable ipv6
  sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
  when: ipv6_disabled
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6

- name: configure | bash
  copy:
    src: global.sh
    dest: /etc/profile.d/global.sh
    mode: 600
