# playbooks/handlers/main.yml
---
- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted

- name: restart sshd
  service:
    name: sshd
    state: restarted
