# playbooks/handlers/main.yml
---
- name: reload systemd
  command: systemctl daemon-reload

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted

- name: restart sshd
  service:
    name: sshd
    state: restarted
