---
dependency:
  name: galaxy
  enabled: False

driver:
  name: vagrant
  provider:
    name: vbox

platforms:
  - name: ubuntu-bionic64
    box: ubuntu/bionic64
    memory: 4096
    cpus: 1

  - name: debian-buster64
    box: debian/buster64
    memory: 4096
    cpus: 1

  - name: centos-8
    box: centos/8
    memory: 4096
    cpus: 1

provisioner:
  name: ansible

verifier:
  name: ansible
